### ISSUE TITLE
update_contributions fails with TypeError

### ISSUE THREAD

**Issue by jensens** [plone/ploneorg.core#29]
``./bin/update_contributions --debug`` with my token fails with::

    DEBUG:contributions:... get contributors for Products.PloneServicesCenter
    Traceback (most recent call last):
      File "./bin/update_contributions", line 294, in <module>
        sys.exit(ploneorg.core.contributions.update_contributions())
      File "/home/jensens/workspace/ploneorg.core/ploneorg/core/contributions.py", line 291, in update_contributions
        json_data = fetch(config)
      File "/home/jensens/workspace/ploneorg.core/ploneorg/core/contributions.py", line 107, in fetch
        data['github']['plone'] = fetch_github(config, 'plone')
      File "/home/jensens/workspace/ploneorg.core/ploneorg/core/contributions.py", line 147, in fetch_github
        for contributor in contributors:
      File "/home/jensens/.buildout/shared-eggs/PyGithub-1.25.2-py2.7.egg/github/PaginatedList.py", line 48, in __iter__
        newElements = self._grow()
      File "/home/jensens/.buildout/shared-eggs/PyGithub-1.25.2-py2.7.egg/github/PaginatedList.py", line 60, in _grow
        newElements = self._fetchNextPage()
      File "/home/jensens/.buildout/shared-eggs/PyGithub-1.25.2-py2.7.egg/github/PaginatedList.py", line 162, in _fetchNextPage
        if len(data) > 0:
    TypeError: object of type 'NoneType' has no len()

**Comment by jensens** [comment]
Looks like this is an API related problem, not ours.
